### ISSUE TITLE
Cython import issue with 3.6.1

### ISSUE THREAD

**Issue by jetuk** [PyTables/PyTables#778]
I have had an issue importing my library which utilises Cython. The error occurred as occurred on appveyor is below. I have isolated the causes of this failure to using pytables-3.6.1. An earlier build using 3.6.0 did not have this issue.

I have since done a test CI build on appveyor with pytables<3.6.1 and this works. See here:

https://github.com/pywr/pywr/pull/790

I'm not sure what has changed between 3.6.0 and 3.6.1, but could it have caused this error?

```
+ python -c "from pywr.solvers import cython_glpk"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "<string>", line 1, in <module>
  File "C:\Python37-x64\Lib\site-packages\pywr\solvers\__init__.py", line 106, in <module>
    from .cython_glpk_edge import CythonGLPKEdgeSolver as cy_CythonGLPKEdgeSolver
  File "pywr\recorders\_recorders.pxd", line 6, in init pywr.solvers.cython_glpk_edge
  File "C:\Python37-x64\Lib\site-packages\pywr\recorders\__init__.py", line 1, in <module>
    from .recorders import *
  File "C:\Python37-x64\Lib\site-packages\pywr\recorders\recorders.py", line 4, in <module>
    from pywr._core import AbstractNode, AbstractStorage
  File "pywr\_core.pyx", line 11, in init pywr._core
AttributeError: type object 'pywr._core.Scenario' has no attribute '__reduce_cython__'
```

**Comment by jetuk** [comment]
I should also add this error has occurred on appveyor (Windows) but not travis (Linux). The latter uses 3.6.1 successfully.

**Comment by tomkooij** [comment]
The Pytables 3.6.0 sdist on PyPI was generated with Cython 0.29.8 (or similar, at least I version that did not yet support the py3.8 C-API changes.)

The Pytables 3.6.0 sdist on PyPI was generated with Cython 0.29.13 (most recent)

Have you tried using the latest cython?

**Comment by jetuk** [comment]
I'm using pip rather than conda. It is using the latest Cython 0.29.13 and the Pytables wheel from Pypi rather than the sdist.

**Comment by tomkooij** [comment]
@jetuk: I had a look at your build. I don't see anything PyTables related. However, you are importing both `pandas` and `tables`. Could that cause some kind of cyclic import hell??
When I google `has no attribute '__reduce_cython__'` that does [pop up.](https://github.com/cython/cython/issues/1953) 

Note that `pytables<3.6.1` installs release 3.5.2 as 3.6.0 has been deleted on PyPI because the 3.6.0 sdist was not compatible with python 3.8.

**Comment by jetuk** [comment]
Yeah this is really confusing to me. We don't do anything besides import pandas and tables. Nothing with their Cython extensions directly. I do wonder if this is just a recent change in Cython and Pytables is my first dependency to be rebuilt with a newer version.

It was my understanding that a fix was applied to Cython to resolve the circular / repeat import issue. 

I haven't managed to reproduce this issue locally yet. I need to get 3.6.1 from conda-forge it seems.

> BTW, I noticed you import your package from the build dir. Perhaps adding a cd .. before python -c import ... will fix this.

I think we move the build folder to `pywr.build` so the import is definitely from the installed package.

**Comment by jetuk** [comment]
Seems like my builds are now working without this change. I'm not sure what changed. There's a new version of Cython though.
