### ISSUE TITLE
Possible performance regression between 2.3.1 and 3.1.1

### ISSUE THREAD

**Issue by taldcroft** [PyTables/PyTables#402]
I have about 100 files which contain a very simple HDF5 data structure with a `data` node of ~10^9 float values.  These data files are hosted on a NetApp server (by external requirements).  My application requires reading small slices of this for all 100 files.  Here is code snippet that is representative of the real code:
```
import tables
vals = {}
for filename in filenames:
    h5 = tables.openFile(os.path.join(filename))
    vals[filename] = h5.root.data[10000:10050]
    h5.close()
```
This is running on CentOS-6 machine with a local network NetApp server using Python 2.7 and numpy 1.8.  Using PyTables 2.3.1 + HDF5 1.8.9, the 100 files are consistently read in a couple of seconds, which is acceptable for our needs.  Using PyTables 3.1.1 + HDF5 1.8.9 (or 1.8.13), the *first* time it runs through, each file read is taking 2 to 10 seconds.  Once a file has been read then subsequent reads of that file are fast, maybe due to the file being cached by the NetApp.

Any clues about what might be going on here?

**Comment by taldcroft** [comment]
Using git bisect I narrowed the regression down to somewhere in these 8 commits:
 https://github.com/PyTables/PyTables/compare/aad7651a3e940a...03890adc38c

I couldn't do better because the next intermediate commit (ccdfa48a65148) failed to build:
```
/export/tom/anaconda/envs/test-pytables/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
src/H5ARRAY.c: In function \u2018H5ARRAYmake\u2019:
src/H5ARRAY.c:150: error: too few arguments to function \u2018H5Dcreate2\u2019
src/H5ARRAY.c:156: error: too few arguments to function \u2018H5Dcreate2\u2019
error: Command "gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DNDEBUG=1 -DHAVE_BZ2_LIB=1 -Iblosc -I/export/tom/anaconda/envs/test-pytables/lib/python2.7/site-packages/numpy/core/include -I/export/tom/anaconda/envs/test-pytables/include -I/export/tom/anaconda/envs/test-pytables/include/python2.7 -c src/H5ARRAY.c -o build/temp.linux-x86_64-2.7/src/H5ARRAY.o -Isrc -DH5Acreate_vers=2 -DH5Aiterate_vers=2 -DH5Eclear_vers=2 -DH5Eprint_vers=2 -DH5Epush_vers=2 -DH5Eset_auto_vers=2 -DH5Eget_auto_vers=2 -DH5Ewalk_vers=2 -DH5E_auto_t_vers=2 -DH5Pget_filter_vers=2 -DH5Tarray_create_vers=2 -DH5Tget_array_dims_vers=2 -DH5Z_class_t_vers=2" failed with exit status 1
```

**Comment by avalentino** [comment]
@taldcroft I'm trying to reproduce the issue but I can't find any performance change between commit 77ebe03 and commit 03890ad.

Which version of the HDF5 library are you using?

This is my configuration:

```
$ env PYTHONPATH=. python -c "import tables as tb; tb.print_versions()"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:  2.3.1+
HDF5 version:      1.8.12
NumPy version:     1.8.2
Numexpr version:   2.4 (not using Intel's VML/MKL)
Zlib version:      1.2.8 (in Python interpreter)
LZO version:       2.06 (Aug 12 2011)
BZIP2 version:     1.0.6 (6-Sept-2010)
Blosc version:     1.1.3 (2010-11-16)
Cython version:    0.20.2
Python version:    2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1]
Platform:          linux2-x86_64
Byte-ordering:     little
Detected cores:    4
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by taldcroft** [comment]
@avalentino - can you see a difference between 2.3.1 and 2.4.0?  And are you using an NFS disk for the file?  Sorry that I didn't explicitly say this before, but there is no problem when using a local disk like /export.  I realize this makes the whole issue tricky and even possibly related to a system misconfiguration on our end, but the current situation for me is that I can't upgrade beyond 2.3.1 because of this.

For a santiy check I also just reproduced my own result that 03890ad is slow initially while 77ebe03 is not.

Here's my version info:
```
(test-pytables)kadi$ python -c "import tables as tb; tb.print_versions()"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:  2.3.1+
HDF5 version:      1.8.14
NumPy version:     1.9.1
Numexpr version:   2.3.1 (not using Intel's VML/MKL)
Zlib version:      1.2.7 (in Python interpreter)
BZIP2 version:     1.0.6 (6-Sept-2010)
Blosc version:     1.1.3 (2010-11-16)
Cython version:    0.22
Python version:    2.7.9 |Continuum Analytics, Inc.| (default, Dec 15 2014, 10:33:51) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Platform:          linux2-x86_64
Byte-ordering:     little
Detected cores:    12
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by taldcroft** [comment]
@avalentino - bad news is that made a mistake earlier in my process, but good news is that I think I have everything straight and have narrowed it down to this single commit: https://github.com/PyTables/PyTables/commit/2fbff78e75436513dc502658a0f9a9361cdff498.

**Comment by avalentino** [comment]
OK @taldcroft, I didn't checked commit 2fbff78, will do ASAP.

In any case if the issue only happens when data files are on NFS it is very hard to me to reproduce.
Also it seems to me that the issue could be an HDF5 issue rather then a problem in PyTables.

My hint is to setup a small C program using HDF5 to check if the problem still persists, in this case we will be sure that he issue is in PyTables.
If the problem is also present in the C program you could try to ask on the hdfgroup mailing list.

**Comment by taldcroft** [comment]
@avalentino - the problem is the call to [H5Oget_info_by_name(loc_id, name, &oinfo, H5P_DEFAULT)](https://github.com/PyTables/PyTables/commit/2fbff78e75436513dc502658a0f9a9361cdff498#diff-74710e3ecbe94109f39de34133e1c8caR243)'

I don't know what is happening in that routine, but this is where all the time is being spent.  If you think this is really an upstream problem in HDF5, I'm OK with putting in the bug report.  However I am completely unfamiliar with the C library and haven't written a real C program in 10 years... So if you could provide me with a small C program which should demonstrate the problem that would be a huge help.

**Comment by taldcroft** [comment]
For what it's worth, h5py still uses the deprecated `H5Gget_objinfo` function and does not suffer from the performance problem.  So I'm even more convinced that is the issue.

This problem was first reported in 2011.  Maybe you can glean some workaround from this?
http://lists.hdfgroup.org/pipermail/hdf-forum_lists.hdfgroup.org/2011-October/005205.html

**Comment by avalentino** [comment]
@taldcroft OK I will try to give a look to it during the week-end.

**Comment by avalentino** [comment]
OK @taldcroft the issue should be fixed in the develop branch.
Can you please confirm that the regression is gone?

**Comment by taldcroft** [comment]
@avalentino - regression is *gone* in the develop branch.  Thanks!  This removes one big blocker for Python 3 migration.  :smile:

Are you planning to post a problem report for the upstream issue in HDF5, or re-open that old thread?

**Comment by avalentino** [comment]
Thanks @taldcroft 

> Are you planning to post a problem report for the upstream issue in HDF5, or re-open that old thread?

If my understanding is correct there is a branch that addresses the issue and the fix will be merged in one of the future releases.
It would be a good idea to give another feedback about this issue.
Please feel free to send a mail and point to this issue if you want.

**Comment by taldcroft** [comment]
@avalentino - do you know if there are plans for a pytables release any time soon?  It looks like it's been almost a year since the last 3.1.1 release so maybe it's time!  :smile:
